### ISSUE TITLE
[MEGATHREAD] - Features MVP 1

### ISSUE THREAD

**Issue by ZenaMel** [Zenahr/github-navigator#1]
- [ ] dump of whatever GitHub API gives on organizations #2 
- [ ] check if static site generation is suitable and scalable #3 
- [ ] model the database model (mongoDB) // Graph-based database? #4 
- [ ] design the views #5 
- [ ] auth (GitHub OAuth) #6
